//
//  SwiftPrompts.swift
//  ProjectName
//
//  Created by Gabriel Alvarado on 3/22/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//


import UIKit

open class SwiftPrompts : NSObject {

    //// Drawing Methods

  open class func drawSwiftPrompt(frame: CGRect,
                                    backgroundColor: UIColor,
                                    headerTxtColor: UIColor,
                                    contentTxtColor: UIColor,
                                    dismissIconButton: UIColor,
                                    promptText: String,
                                    textSize: CGFloat,
                                    headerText: String,
                                    headerSize: CGFloat) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(roundedRect: frame, cornerRadius: 12)
        backgroundColor.setFill()
        rectanglePath.fill()

        //// Text Drawing
        let textRect = CGRect(x: frame.minX + 13, y: frame.minY + 56, width: frame.width - 26, height: frame.height - 109)
        let textStyle = NSMutableParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
        textStyle.alignment = NSTextAlignment.center

        let textFontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Light", size: textSize)!, NSForegroundColorAttributeName: contentTxtColor, NSParagraphStyleAttributeName: textStyle]

        let textTextHeight: CGFloat = NSString(string: promptText).boundingRect(with: CGSize(width: textRect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: textFontAttributes, context: nil).size.height
        context?.saveGState()
        context?.clip(to: textRect);
        NSString(string: promptText).draw(in: CGRect(x: textRect.minX, y: textRect.minY + (textRect.height - textTextHeight) / 2, width: textRect.width, height: textTextHeight), withAttributes: textFontAttributes)
        context?.restoreGState()


        //// Text 2 Drawing
        let text2Rect = CGRect(x: frame.minX + floor(frame.width * 0.05333 + 0.5),
                                   y: frame.minY + 20,
                                   width: floor(frame.width * 0.93778 + 0.5) - floor(frame.width * 0.05333 + 0.5),
                                   height: 34)

        let text2Style = NSMutableParagraphStyle.default.mutableCopy() as! NSMutableParagraphStyle
        text2Style.alignment = NSTextAlignment.center

        let text2FontAttributes = [NSFontAttributeName: UIFont(name: "HelveticaNeue-Light", size: headerSize)!, NSForegroundColorAttributeName: headerTxtColor, NSParagraphStyleAttributeName: text2Style]

        let text2TextHeight: CGFloat = NSString(string: headerText).boundingRect(with: CGSize(width: text2Rect.width, height: CGFloat.infinity), options: NSStringDrawingOptions.usesLineFragmentOrigin, attributes: text2FontAttributes, context: nil).size.height
        context?.saveGState()
        context?.clip(to: text2Rect);
        NSString(string: headerText).draw(in: CGRect(x: text2Rect.minX, y: text2Rect.minY + (text2Rect.height - text2TextHeight) / 2, width: text2Rect.width, height: text2TextHeight), withAttributes: text2FontAttributes)
        context?.restoreGState()


    }

}

@objc protocol StyleKitSettableImage {
    func setImage(_ image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(_ image: UIImage!)
}
